### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by marcominetti** [SkyLined/cWinPerfCounter#1]
Hi there, I'm trying to poll three perfcounter instances every 1000ms... It seems that the fnGetValue is CPU hungry... is that normal (performance counters are CPU hungry) or is there any optimization to be done? any hints?

**Comment by SkyLined** [comment]
I'm on holiday at the moment and won't be near a computer for another week
and a half.

it's supposed to be quick; I poll CPU usage tens of times a second without
any significant CPU usage.

I'd need mode details to guess what's going wrong for you, such as the type
of hardware you're using and which counters you're polling.

cheers,

SkyLined

**Comment by marcominetti** [comment]
Enjoy your holidays, hope hearing from u when back. Cheers!

**Comment by SkyLined** [comment]
I'm back from holiday, but I cannot help you unless you give me the details I requested. A copy of your code may also shed some light on the issue.

**Comment by marcominetti** [comment]
I was pasting my code and I've just caught that a leftover was causing performance counter get value every ms....... ;S Sorry! LOL
